name: trivy scans

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/trivy-scans.yml'

env:
  OTELCOL_IMAGE: otelcol:latest

jobs:
  trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run trivy filesystem scan
        uses: aquasecurity/trivy-action@0.2.5
        with:
          scan-type: 'fs'
          scan-ref: '.'
          skip-dirs: 'examples,internal/buildscripts,tests'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

  trivy-image-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.1
      - id: module-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-go-modules
        with:
          path: |
            /home/runner/go/pkg/mod
            /home/runner/.cache/go-build
          key: v1-go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.mod', '**/go.sum') }}
      - run: make docker-otelcol
        env:
          DOCKER_BUILDKIT: '1'
      - name: Run trivy image scan
        uses: aquasecurity/trivy-action@0.2.5
        with:
          scan-type: 'image'
          image-ref: ${{ env.OTELCOL_IMAGE }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
